route:
  receiver: 'telegram'
  routes:
  - match:
    severity: 'critical'
    receiver: 'telegram_kt'
      #    continue: true
      #  - match:
      #    receiver: 'telegram'
templates:
  - '/etc/alertmanager/templates/*.tmpl'
receivers:
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: '***REMOVED***'
        chat_id: -663588500
        message: '{{ template "telegram_simple.html.message" . }}'
        parse_mode: HTML

  - name: 'telegram_kt'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: '***REMOVED***'
        chat_id: -1001677807665
        message: '{{ template "telegram_simple.html.message" . }}'
        parse_mode: HTML
