devices:
  - name: anfisa_router
    address: 192.168.130.1
    user: prometheus
    password: ***REMOVED***
  - name: anfisa_lte
    address: 172.16.130.1
    user: prometheus
    password: ***REMOVED***

features:
  bgp: false
  dhcp: true
  dhcpv6: false
  dhcpl: false
  routes: true
  pools: false
  optics: false
  health: true
  lte: true
  netwatch: true
