devices:
  - name: core_router
    address: 172.24.0.1
    user: prometheus
    password: ***REMOVED***
  - name: raskat_router
    address: 172.24.98.1
    user: prometheus
    password: ***REMOVED***

features:
  bgp: false
  dhcp: true
  dhcpv6: false
  dhcpl: false
  routes: true
  pools: false
  optics: false
  health: true
  lte: true
  netwatch: true
