devices:
    user: prometheus
    password: ***REMOVED***
  - name: shalanda_lte
    address: 172.16.120.1
    user: prometheus
    password: ***REMOVED***

features:
  bgp: false
  dhcp: true
  dhcpv6: false
  dhcpl: false
  routes: true
  pools: false
  optics: false
  health: true
  lte: true
  netwatch: true
