global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'host-shalanda'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 192.168.120.201:9100
        - 192.168.120.202:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '$1'

  - job_name: "mikrotik"
    static_configs:
      - targets:
        - mikrotik:9436
    metrics_path: /metrics

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - '172.24.0.65:9093'
