global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'host-Ulianov'
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert_ru.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 192.168.140.201:9100
        - 192.168.140.202:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '$1'

  - job_name: 'snmp_apcups'
    static_configs:
      - targets:
        - 192.168.140.6
        - 192.168.140.7
    metrics_path: /snmp
    params:
      module: [apcups]
    scrape_interval: 3m
    scrape_timeout: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'snmp_mikrotik'
    static_configs:
      - targets:
        - 192.168.140.1
    metrics_path: /snmp
    params:
      module:
        - mikrotik
    scrape_interval: 2m
    scrape_timeout: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.

  - job_name: ipmi
    params:
      module: ['default']
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /ipmi
    scheme: http
    static_configs:
      - targets:
        - 192.168.140.9
        - 192.168.140.10
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: ${1}
        action: replace
      - source_labels: [__param_target]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: ${1}
        action: replace
      - separator: ;
        regex: .*
        target_label: __address__
        replacement: ipmi:9290
        action: replace

  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
    static_configs:
      - targets:
        - '192.168.140.101:9090'
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - '172.24.0.65:9093'

