global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'host-Anfisa'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 192.168.130.201:9100
        - 192.168.130.202:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '$1'

  - job_name: 'snmp_apcups'
    static_configs:
      - targets:
        - 192.168.130.6
        - 192.168.130.7
    metrics_path: /snmp
    params:
      module: [apcups]
    scrape_interval: 3m
    scrape_timeout: 3m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.

  - job_name: 'snmp_mikrotik'
    static_configs:
      - targets:
        - 192.168.130.1
    metrics_path: /snmp
    params:
      module:
        - mikrotik
    scrape_interval: 5m
    scrape_timeout: 5m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp:9116  # The SNMP exporter's real hostname:port.

          #  - job_name: "mikrotik"
          #    static_configs:
          #      - targets:
          #        - mikrotik:9436
          #    metrics_path: /metrics
          #
          #  - job_name: 'federate'
          #    honor_labels: true
          #    metrics_path: '/federate'
          #    params:
          #      'match[]':
          #        - '{job="prometheus"}'
          #    static_configs:
          #      - targets:
          #        - '192.168.120.101:9090'
